#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${CODEFLARE_ENV:-$HOME/.config/codeflare/.env}"
TMP_CONFIG=""
CLOUDFLARED_TUNNEL_ID=""
CLOUDFLARED_CREDENTIALS_PATH=""
OPENCODE_PUBLIC_HOSTNAME="code.example.com"
OPENCODE_LISTEN_HOST="127.0.0.1"
OPENCODE_PORT="4096"
CODEFLARE_QUIET_DISCONNECT_LOGS="false"
CODEFLARE_FORCE_DNS="false"
CODEFLARE_TUNNEL_PROTOCOL="quic"

usage() {
  cat <<USAGE
Usage:
  codeflare [up] [PROJECT_DIR]
  codeflare local [PROJECT_DIR]
  codeflare tunnel
  codeflare dns
  codeflare check

Commands:
  up       Start OpenCode locally and run Cloudflare tunnel (default).
  local    Start only OpenCode locally.
  tunnel   Start only Cloudflare tunnel (expects OpenCode already running).
  dns      Ensure DNS route points to the configured tunnel.
  check    Validate config and dependencies.
USAGE
}

load_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Missing env file: $ENV_FILE" >&2
    echo "Run setup.sh from the repo root to generate it." >&2
    exit 1
  fi
  CLOUDFLARED_TUNNEL_ID="$(read_env_var CLOUDFLARED_TUNNEL_ID || true)"
  CLOUDFLARED_CREDENTIALS_PATH="$(read_env_var CLOUDFLARED_CREDENTIALS_PATH || true)"
  OPENCODE_PUBLIC_HOSTNAME="$(read_env_var OPENCODE_PUBLIC_HOSTNAME || printf '%s' "$OPENCODE_PUBLIC_HOSTNAME")"
  OPENCODE_LISTEN_HOST="$(read_env_var OPENCODE_LISTEN_HOST || printf '%s' "$OPENCODE_LISTEN_HOST")"
  OPENCODE_PORT="$(read_env_var OPENCODE_PORT || printf '%s' "$OPENCODE_PORT")"
  CODEFLARE_QUIET_DISCONNECT_LOGS="$(read_env_var CODEFLARE_QUIET_DISCONNECT_LOGS || printf '%s' "$CODEFLARE_QUIET_DISCONNECT_LOGS")"
  CODEFLARE_FORCE_DNS="$(read_env_var CODEFLARE_FORCE_DNS || printf '%s' "$CODEFLARE_FORCE_DNS")"
  CODEFLARE_TUNNEL_PROTOCOL="$(read_env_var CODEFLARE_TUNNEL_PROTOCOL || printf '%s' "$CODEFLARE_TUNNEL_PROTOCOL")"
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd" >&2
    exit 1
  fi
}

read_env_var() {
  local key="$1"
  local line raw
  line="$(grep -E "^[[:space:]]*${key}=" "$ENV_FILE" | tail -n 1 || true)"
  if [[ -z "$line" ]]; then
    return 1
  fi
  raw="${line#*=}"
  raw="$(printf '%s' "$raw" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
  if [[ "$raw" =~ ^\".*\"$ || "$raw" =~ ^\'.*\'$ ]]; then
    raw="${raw:1:${#raw}-2}"
  fi
  printf '%s' "$raw"
}

valid_port() {
  local p="$1"
  [[ "$p" =~ ^[0-9]+$ ]] || return 1
  (( p >= 1 && p <= 65535 ))
}

valid_hostname() {
  local h="$1"
  [[ "$h" =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$ ]]
}

valid_tunnel_protocol() {
  local p="$1"
  [[ "$p" == "quic" || "$p" == "http2" ]]
}

validate_runtime_config() {
  if ! valid_hostname "$OPENCODE_PUBLIC_HOSTNAME"; then
    echo "OPENCODE_PUBLIC_HOSTNAME is invalid: $OPENCODE_PUBLIC_HOSTNAME" >&2
    exit 1
  fi
  if ! valid_port "$OPENCODE_PORT"; then
    echo "OPENCODE_PORT must be an integer between 1 and 65535 (got: $OPENCODE_PORT)" >&2
    exit 1
  fi
  if ! valid_tunnel_protocol "$CODEFLARE_TUNNEL_PROTOCOL"; then
    echo "CODEFLARE_TUNNEL_PROTOCOL must be one of: quic, http2 (got: $CODEFLARE_TUNNEL_PROTOCOL)" >&2
    exit 1
  fi
}

init_tmp_config() {
  if [[ -z "$TMP_CONFIG" ]]; then
    TMP_CONFIG="$(mktemp /tmp/codeflare-tunnel.XXXXXX.yml)"
  fi
}

cleanup_tmp_config() {
  if [[ -n "$TMP_CONFIG" && -f "$TMP_CONFIG" ]]; then
    rm -f "$TMP_CONFIG"
  fi
}

run_cloudflared() {
  local quiet="${CODEFLARE_QUIET_DISCONNECT_LOGS:-false}"
  local protocol="${CODEFLARE_TUNNEL_PROTOCOL:-quic}"
  if [[ "$quiet" == "true" ]]; then
    cloudflared tunnel --protocol "$protocol" --config "$TMP_CONFIG" run 2>&1 | awk '
      /canceled by remote with error code 0/ { next }
      { print }
    '
  else
    cloudflared tunnel --protocol "$protocol" --config "$TMP_CONFIG" run
  fi
}

print_runtime_notice() {
  cat >&2 <<'NOTICE'

============================================================
 IMPORTANT
 1) CONFIGURE CLOUDFLARE ACCESS FOR YOUR PUBLIC HOSTNAME
    TO KEEP THE ENDPOINT PRIVATE.
 2) OPENCODE WEB MAY OPEN A LOCAL BROWSER TAB AUTOMATICALLY.
    YOU CAN SAFELY CLOSE THAT TAB.
============================================================

NOTICE
}

resolve_tunnel_id() {
  local id="$CLOUDFLARED_TUNNEL_ID"
  if [[ -z "$id" && -n "${CLOUDFLARED_CREDENTIALS_PATH:-}" ]]; then
    local inferred
    inferred="$(basename "$CLOUDFLARED_CREDENTIALS_PATH" .json)"
    if [[ "$inferred" =~ ^[0-9a-fA-F-]{36}$ ]]; then
      id="$inferred"
    fi
  fi
  if [[ -z "$id" ]]; then
    echo "CLOUDFLARED_TUNNEL_ID is required (or inferable from CLOUDFLARED_CREDENTIALS_PATH)." >&2
    exit 1
  fi
  printf '%s' "$id"
}

write_tunnel_config() {
  local tunnel_id="$1"
  local creds="$2"
  local host="$3"
  local listen_host="$4"
  local port="$5"

  cat > "$TMP_CONFIG" <<CFG
# Generated by codeflare
tunnel: ${tunnel_id}
credentials-file: ${creds}
ingress:
  - hostname: ${host}
    service: http://${listen_host}:${port}
  - service: http_status:404
CFG
}

ensure_dns() {
  local tunnel_id="$1"
  local host="$2"
  local force="$CODEFLARE_FORCE_DNS"
  local output

  if [[ "$force" == "true" ]]; then
    cloudflared tunnel route dns -f "$tunnel_id" "$host" >/dev/null
    return
  fi

  output="$(cloudflared tunnel route dns "$tunnel_id" "$host" 2>&1)" || {
    if printf '%s' "$output" | grep -qi "already exists"; then
      echo "DNS record already exists for ${host}; keeping existing record (set CODEFLARE_FORCE_DNS=true to overwrite)." >&2
      return
    fi
    printf '%s\n' "$output" >&2
    return 1
  }
}

wait_for_local_opencode() {
  local listen_host="$1"
  local port="$2"
  local pid="$3"
  local health_url="http://${listen_host}:${port}/"
  local attempts=20
  local i

  require_cmd curl

  for i in $(seq 1 "$attempts"); do
    if ! kill -0 "$pid" >/dev/null 2>&1; then
      echo "OpenCode process exited before becoming ready." >&2
      return 1
    fi
    if curl -fsS "$health_url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.5
  done
  echo "Timed out waiting for OpenCode at $health_url" >&2
  return 1
}

run_local() {
  local project_dir="$1"
  local listen_host="$2"
  local port="$3"

  if [[ ! -d "$project_dir" ]]; then
    echo "Project directory does not exist: $project_dir" >&2
    exit 1
  fi

  echo "Starting OpenCode in ${project_dir} on http://${listen_host}:${port}"
  cd "$project_dir"
  opencode web --hostname "$listen_host" --port "$port"
}

run_tunnel() {
  local tunnel_id="$1"
  local creds="$2"
  local host="$3"
  local listen_host="$4"
  local port="$5"

  if [[ ! -f "$creds" ]]; then
    echo "Tunnel credentials not found: $creds" >&2
    exit 1
  fi

  echo "Ensuring DNS route for ${host} -> tunnel ${tunnel_id}"
  ensure_dns "$tunnel_id" "$host"

  write_tunnel_config "$tunnel_id" "$creds" "$host" "$listen_host" "$port"
  echo "Starting cloudflared tunnel for https://${host} -> http://${listen_host}:${port}"
  run_cloudflared
}

run_check() {
  require_cmd opencode
  require_cmd cloudflared

  local tunnel_id creds host listen_host port
  tunnel_id="$(resolve_tunnel_id)"
  creds="${CLOUDFLARED_CREDENTIALS_PATH:-$HOME/.cloudflared/${tunnel_id}.json}"
  host="$OPENCODE_PUBLIC_HOSTNAME"
  listen_host="$OPENCODE_LISTEN_HOST"
  port="$OPENCODE_PORT"

  if [[ ! -f "$creds" ]]; then
    echo "Missing credentials file: $creds" >&2
    exit 1
  fi
  if ! cloudflared tunnel info "$tunnel_id" >/dev/null 2>&1; then
    echo "Tunnel ID not found or not accessible: $tunnel_id" >&2
    exit 1
  fi

  echo "Config OK"
  echo "  Hostname:      $host"
  echo "  Tunnel ID:     $tunnel_id"
  echo "  Credentials:   $creds"
  echo "  Local service: http://${listen_host}:${port}"
}

main() {
  local cmd="${1:-up}"
  if [[ $# -gt 0 ]]; then
    shift
  fi

  if [[ "$cmd" == "help" || "$cmd" == "--help" || "$cmd" == "-h" ]]; then
    usage
    exit 0
  fi

  load_env
  validate_runtime_config

  local project_dir="${1:-$PWD}"
  local tunnel_id creds host listen_host port

  tunnel_id="$(resolve_tunnel_id)"
  creds="${CLOUDFLARED_CREDENTIALS_PATH:-$HOME/.cloudflared/${tunnel_id}.json}"
  host="$OPENCODE_PUBLIC_HOSTNAME"
  listen_host="$OPENCODE_LISTEN_HOST"
  port="$OPENCODE_PORT"

  case "$cmd" in
    up)
      require_cmd opencode
      require_cmd cloudflared

      if [[ ! -f "$creds" ]]; then
        echo "Tunnel credentials not found: $creds" >&2
        exit 1
      fi
      if [[ ! -d "$project_dir" ]]; then
        echo "Project directory does not exist: $project_dir" >&2
        exit 1
      fi

      ensure_dns "$tunnel_id" "$host"
      init_tmp_config
      write_tunnel_config "$tunnel_id" "$creds" "$host" "$listen_host" "$port"

      (
        cd "$project_dir"
        opencode web --hostname "$listen_host" --port "$port"
      ) &
      opencode_pid=$!

      cleanup() {
        if kill -0 "$opencode_pid" >/dev/null 2>&1; then
          kill "$opencode_pid" >/dev/null 2>&1 || true
        fi
        cleanup_tmp_config
      }
      trap cleanup EXIT INT TERM
      wait_for_local_opencode "$listen_host" "$port" "$opencode_pid"

      echo "OpenCode URL (local): http://${listen_host}:${port}"
      echo "OpenCode URL (public): https://${host}"
      print_runtime_notice
      run_cloudflared
      ;;
    local)
      require_cmd opencode
      run_local "$project_dir" "$listen_host" "$port"
      ;;
    tunnel)
      require_cmd cloudflared
      init_tmp_config
      trap cleanup_tmp_config EXIT INT TERM
      run_tunnel "$tunnel_id" "$creds" "$host" "$listen_host" "$port"
      ;;
    dns)
      require_cmd cloudflared
      ensure_dns "$tunnel_id" "$host"
      echo "DNS route set: ${host} -> ${tunnel_id}"
      ;;
    check)
      run_check
      ;;
    -h|--help|help)
      usage
      ;;
    *)
      echo "Unknown command: $cmd" >&2
      usage
      exit 1
      ;;
  esac
}

main "$@"
